
/*
 * 
 */

package pe.com.creararequipa.wcfnovatronicqa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Nov 04 21:57:40 COT 2020
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "CanalesUBAWCFImplService", 
                  wsdlLocation = "https://transactqa.compartamos.com.pe:8443/WCFCanalesUBA/wmProcesarTramaUBAResponse/CanalesUBAWCF?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class CanalesUBAWCFImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "CanalesUBAWCFImplService");
    public final static QName CanalesUBAWCFImplPort = new QName("http://tempuri.org/", "CanalesUBAWCFImplPort");
    static {
        URL url = null;
        try {
            url = new URL("https://transactqa.compartamos.com.pe:8443/WCFCanalesUBA/wmProcesarTramaUBAResponse/CanalesUBAWCF?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://transactqa.compartamos.com.pe:8443/WCFCanalesUBA/wmProcesarTramaUBAResponse/CanalesUBAWCF?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CanalesUBAWCFImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CanalesUBAWCFImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CanalesUBAWCFImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CanalesUBAWCFImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public CanalesUBAWCFImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CanalesUBAWCFImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICanalesUBAWCF
     */
    @WebEndpoint(name = "CanalesUBAWCFImplPort")
    public ICanalesUBAWCF getCanalesUBAWCFImplPort() {
        return super.getPort(CanalesUBAWCFImplPort, ICanalesUBAWCF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICanalesUBAWCF
     */
    @WebEndpoint(name = "CanalesUBAWCFImplPort")
    public ICanalesUBAWCF getCanalesUBAWCFImplPort(WebServiceFeature... features) {
        return super.getPort(CanalesUBAWCFImplPort, ICanalesUBAWCF.class, features);
    }

}
