package pe.com.creararequipa.wcfnovatronicqa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Nov 04 21:57:40 COT 2020
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "ICanalesUBAWCF")
@XmlSeeAlso({ObjectFactory.class})
public interface ICanalesUBAWCF {

    @WebMethod(action = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaPinPad")
    @RequestWrapper(localName = "wmProcesarTramaPinPad", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.WmProcesarTramaPinPad")
    @ResponseWrapper(localName = "wmProcesarTramaPinPadResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.WmProcesarTramaPinPadResponse")
    @WebResult(name = "wmProcesarTramaPinPadResult", targetNamespace = "http://tempuri.org/")
    public pe.com.creararequipa.wcfnovatronicqa.ServicioCanalesRPTRQT wmProcesarTramaPinPad(
        @WebParam(name = "toServicioCanales", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronicqa.ServicioCanalesRPTRQT toServicioCanales
    );

    @WebMethod(operationName = "ProcesarTramaMonitoreoFraude", action = "http://tempuri.org/ICanalesUBAWCF/ProcesarTramaMonitoreoFraude")
    @RequestWrapper(localName = "ProcesarTramaMonitoreoFraude", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.ProcesarTramaMonitoreoFraude")
    @ResponseWrapper(localName = "ProcesarTramaMonitoreoFraudeResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.ProcesarTramaMonitoreoFraudeResponse")
    public void procesarTramaMonitoreoFraude(
        @WebParam(name = "datosRqt", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronicqa.MonitoreoFraude datosRqt
    );

    @WebMethod(action = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaUBA")
    @RequestWrapper(localName = "wmProcesarTramaUBA", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.WmProcesarTramaUBA")
    @ResponseWrapper(localName = "wmProcesarTramaUBAResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronicqa.WmProcesarTramaUBAResponse")
    @WebResult(name = "wmProcesarTramaUBAResult", targetNamespace = "http://tempuri.org/")
    public pe.com.creararequipa.wcfnovatronicqa.ServicioCanalesRPTRQT wmProcesarTramaUBA(
        @WebParam(name = "toServicioCanales", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronicqa.ServicioCanalesRPTRQT toServicioCanales
    );
}
