package pe.com.creararequipa.wcfnovatronic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Nov 04 15:43:39 COT 2020
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://tempuri.org/", name = "ICanalesUBAWCF")
@XmlSeeAlso({ObjectFactory.class})
public interface ICanalesUBAWCF {

    @WebMethod(action = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaPinPad")
    @Action(input = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaPinPad", output = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaPinPadResponse")
    @RequestWrapper(localName = "wmProcesarTramaPinPad", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.WmProcesarTramaPinPad")
    @ResponseWrapper(localName = "wmProcesarTramaPinPadResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.WmProcesarTramaPinPadResponse")
    @WebResult(name = "wmProcesarTramaPinPadResult", targetNamespace = "http://tempuri.org/")
    public pe.com.creararequipa.wcfnovatronic.ServicioCanalesRPTRQT wmProcesarTramaPinPad(
        @WebParam(name = "toServicioCanales", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronic.ServicioCanalesRPTRQT toServicioCanales
    );

    @WebMethod(action = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaUBA")
    @Action(input = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaUBA", output = "http://tempuri.org/ICanalesUBAWCF/wmProcesarTramaUBAResponse")
    @RequestWrapper(localName = "wmProcesarTramaUBA", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.WmProcesarTramaUBA")
    @ResponseWrapper(localName = "wmProcesarTramaUBAResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.WmProcesarTramaUBAResponse")
    @WebResult(name = "wmProcesarTramaUBAResult", targetNamespace = "http://tempuri.org/")
    public pe.com.creararequipa.wcfnovatronic.ServicioCanalesRPTRQT wmProcesarTramaUBA(
        @WebParam(name = "toServicioCanales", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronic.ServicioCanalesRPTRQT toServicioCanales
    );

    @WebMethod(operationName = "ProcesarTramaMonitoreoFraude", action = "http://tempuri.org/ICanalesUBAWCF/ProcesarTramaMonitoreoFraude")
    @Action(input = "http://tempuri.org/ICanalesUBAWCF/ProcesarTramaMonitoreoFraude", output = "http://tempuri.org/ICanalesUBAWCF/ProcesarTramaMonitoreoFraudeResponse")
    @RequestWrapper(localName = "ProcesarTramaMonitoreoFraude", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.ProcesarTramaMonitoreoFraude")
    @ResponseWrapper(localName = "ProcesarTramaMonitoreoFraudeResponse", targetNamespace = "http://tempuri.org/", className = "pe.com.creararequipa.wcfnovatronic.ProcesarTramaMonitoreoFraudeResponse")
    public void procesarTramaMonitoreoFraude(
        @WebParam(name = "datosRqt", targetNamespace = "http://tempuri.org/")
        pe.com.creararequipa.wcfnovatronic.MonitoreoFraude datosRqt
    );
}
